# Generated by Django 2.2.6 on 2019-11-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseriesdatum',
            old_name='instrument',
            new_name='sensor',
        ),
    ]
